server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
#  ConnectTimeout: 5000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 # 这个配置也是接口调用的超时配置，但开启feign对hystrix的支持才生效
feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 由于ribbon配置无效，改用feign的配置
        readTimeout: 5000
  hystrix:
    enabled: false # 开启feign对hystrix的支持